### ISSUE TITLE
Using the options object

### ISSUE THREAD

**Issue by robynjayqueerie** [RandomStudio/omxconductor#12]
## Feature request

Not really a feature request and not a bug. But I am having difficulty seeing how to get Omxplayer options fed through the config object in the command line. eg trying to use the subtitles option --subtitles path        External subtitles in UTF-8 srt format 
The only way I can get the config object to accept anything like this is the following
player = new Player('media/tenseconds.mp4', {subtitles: 'custom.srt',loop:false})
The subtitles appears in the object but not in the Omx command. eg
omx config:
 {
  layer: 1,
  dBusId: 'org.mpris.MediaPlayer2.omxplayer',
  audioOutput: 'local',
  backgroundColor: '0xff000000',
  noBackgroundColor: true,
  loop: false,
  testModeOnly: false,
  progressInterval: 16,
  initVolume: 1,
  noKeys: true,
  noOsd: true,
  orientation: 0,
  subtitles: 'custom.srt'
}
**************** ready event: { result: 'Playing', attemptsLeft: 9 }
open result: {
  filePath: '/home/pi/ptzcontrol/media/tenseconds.mp4',
  command: 'omxplayer "/home/pi/ptzcontrol/media/tenseconds.mp4" -o local  --dbus_name org.mpris.MediaPlayer2.omxplayer  --layer 1 --vol 0 --no-keys --no-osd --orientation 0 < omxpipe1',
  playing: true
}

You don't really explain in the Read.me how to use the config object. If I try to use --subtitles it is thrown out and obviously leaving the -- off seems the .getSettings() function does not set the command up properly.

I have tried for a few hours to see how to do this, just wondering what I am missing.
Thanks in advance
Robyn

**Comment by anselanza** [comment]
Hi and thanks for pointing this out. Indeed the options is not well documented.

The other problem is that the options are not complete, i.e. they don't map 1:1 with the options that omxplayer actually provides.

You can get an idea of the current list of options by looking at the src/defaults.ts 
```
export const defaultOptions: PlayerSettings = {
  layer: 1,
  dBusId: "org.mpris.MediaPlayer2.omxplayer",
  audioOutput: "local" as AudioOutput,
  backgroundColor: "0xff000000",
  noBackgroundColor: true,
  loop: true,
  testModeOnly: false,
  progressInterval: 16,
  initVolume: 1,
  noKeys: true,
  noOsd: true,
  orientation: 0,
};
```

Which as you can see, does not currently include subtitles.

I think I'm going to put in a few minutes today to add that feature, since it ought to be there.

Anything else you need, while I'm at it?

**Comment by anselanza** [comment]
Done! 

Added as per https://github.com/RandomStudio/omxconductor/commit/25b687e79ea374e11f3e668a4ce6197c003a99d5

You can simply update to v 2.2.3 if you'd like to pass through subtitles path
```
npm upgrade omxconductor
```

**Comment by robynjayqueerie** [comment]
Thanks, I spent some time prowling through the code yesterday and came to that conclusion that only a subset of the options was mapped through. I thought I could see how to change that but it needed a fork and recompile which I was not confident I could do. Thanks for adding the subtitles. That was the main one I needed. I will press on and see how I go.

**Comment by anselanza** [comment]
> only a subset of the options was mapped through

Yes. And I am reconsidering whether this was the right choice! I'm going to start working through the options to ensure all of them are represented in the API (https://github.com/RandomStudio/omxconductor/projects/1) 

>  I thought I could see how to change that but it needed a fork and recompile which I was not confident I could do.

Let me know if you need any help with that. The steps are
- fork the repo
- clone the forked version
- run `npm install` in that folder
- make your changes
- run `npm run build` to compile

Of course, there's a little more to it when needing to test, etc. especially if on a Raspberry Pi. I personally use `sudo npm link` inside the version I'm working on, then `npm link omxconductor` will link (rather than install) the local version of the library inside another project to test with. But of course all of this requires some familiarity with NPM, TypeScript and possibly SSH (or Visual Studio Code remote development) if you need to work on a development machine that is not the Raspberry Pi itself. 

Again, l'd be happy to give pointers if you're interested in learning how to contribute.

**Comment by robynjayqueerie** [comment]
Thanks for that Stephen, I was thinking of adding the font and size as well so I may have a go at it - Robyn
